vim.api.nvim_set_hl(0, "NormalFloat", { link = "Normal" })
vim.api.nvim_set_hl(0, "FloatTitle", { link = "Normal" })
vim.api.nvim_set_hl(0, "FloatBorder", { link = "Normal" })
vim.api.nvim_set_hl(0, "LspInlayHint", { link = "Comment" })
vim.api.nvim_set_hl(0, "LspFloatWinNormal", { link = "Normal" })
-- vim.api.nvim_set_hl(0, "WinBar", { fg = "#458e88", undercurl = true })
-- vim.api.nvim_set_hl(0, "WinBarNC", { fg = "#666777", undercurl = true })
vim.api.nvim_set_hl(0, "WhichKeyFloat", { link = "Normal" })
vim.api.nvim_set_hl(0, "LspCodeLens", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "LspCodeLensText", { link = "WarningMsg" })
vim.api.nvim_set_hl(0, "LspCodeLensTextSign", { link = "LspCodeLensText" })
vim.api.nvim_set_hl(0, "LspCodeLensTextSeparator", { link = "Boolean" })
